# Cloudflare Pages configuration for backup deployment
name = "pixelated-backup"
compatibility_date = "2025-01-20"
compatibility_flags = ["nodejs_compat"]
account_id = "your-account-id-here" # Replace with your Cloudflare account ID

# Pages configuration
pages_build_output_dir = "./dist"

# Environment variables for production
[env.local]
name = "pixelated-backup"

[env.local.vars]
NODE_ENV = "production"
CLOUDFLARE_BUILD = "1"
SENTRY_PROJECT = "pixelated-cloudflare"

# KV namespace for session storage (optional)
[[env.local.kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id" # Replace with your KV namespace ID
preview_id = "your-preview-kv-namespace-id" # Replace with preview KV namespace ID

# Development environment
[env.preview]
name = "pixelated-backup-preview"

[env.preview.vars]
NODE_ENV = "development"
CLOUDFLARE_BUILD = "1"

# Build configuration
[build]
command = "pnpm run build:cloudflare"
cwd = "./"

# Pages build settings
[pages]
compatibility_date = "2025-01-20"
compatibility_flags = ["nodejs_compat"]

# Functions configuration
[pages.functions]
max_duration = 30

# Headers configuration
[[pages.headers]]
for = "/*"

[pages.headers.values]
"X-Backup-Site" = "true"
"X-Powered-By" = "Cloudflare Pages"
"X-Deployment" = "backup"

# Cache configuration for static assets
[[pages.headers]]
for = "/css/*"

[pages.headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/js/*"

[pages.headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/images/*"

[pages.headers.values]
"Cache-Control" = "public, max-age=86400"

# Redirects for backup site
[[pages.redirects]]
from = "/admin/*"
to = "https://pixelatedempathy.com/admin/:splat"
status = 302

# Security redirects
[[pages.redirects]]
from = "/api/webhooks/*"
to = "https://pixelatedempathy.com/api/webhooks/:splat"
status = 302 