# Cloudflare Pages configuration for Pixelated
name = "pixelated-backup"
compatibility_date = "2025-01-20"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "pnpm run build"
cwd = "./"

# KV namespace bindings for session storage
[[kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id" # Replace with your actual KV namespace ID

[env.preview]
[[env.preview.kv_namespaces]]
binding = "SESSION"
id = "your-preview-kv-namespace-id" # Replace with your preview KV namespace ID

# Environment variables
[vars]
NODE_ENV = "production"
CLOUDFLARE_BUILD = "1"

[env.preview.vars]
NODE_ENV = "preview"
CLOUDFLARE_BUILD = "1" 