name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Environment variables can be defined here
env:
  NODE_ENV: production

jobs:
  setup:
    name: Setup Versions
    uses: ./.github/workflows/setup-versions.yml

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ needs.setup.outputs.pnpm-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        timeout-minutes: 10
        env:
          DISABLE_WEB_FONTS: 'true'
          NODE_OPTIONS: '--max-old-space-size=8192'
