name: Schedule Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

# Environment variables can be defined here
env:
  NODE_ENV: production

jobs:
  setup:
    name: Setup Versions
    uses: ./.github/workflows/setup-versions.yml

  schedule-posts:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ needs.setup.outputs.pnpm-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run post scheduler
        run: pnpm run schedule-posts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
